<Project Sdk="Microsoft.NET.Sdk">
    <!-- Library -->
    <PropertyGroup>
        <RootNamespace>Layers.Core</RootNamespace>
        <IsAotCompatible>true</IsAotCompatible>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <!-- Packages -->
    <ItemGroup>
        <PackageReference Include="Microsoft.Windows.CsWin32" PrivateAssets="all" />
        <PackageReference Include="System.IO.Hashing" />
    </ItemGroup>

    <!-- Test Access -->
    <ItemGroup>
        <InternalsVisibleTo Include="Layers.Tests" />
    </ItemGroup>
</Project>
